test_file_operation:test.cpp file_operation.cpp file_operation.h return_status.cpp return_status.h
	g++ test.cpp file_operation.cpp return_status.cpp -o test_file_operation -std=c++11
clean:
	rm -rf 1.txt test_file_operation
